# mysql配置
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://192.168.106.191:3306/reports?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
db.username=report
db.password=XS14*16sq

# 连接池配置
pool.maximumPoolSize=10
pool.minimumIdle=5
pool.connectionTimeout=30000
pool.idleTimeout=600000
pool.maxLifetime=1800000