# 设置日志级别
org.slf4j.simpleLogger.defaultLogLevel=info

# 输出到文件
org.slf4j.simpleLogger.logFile=taskbot.log

# 是否在控制台输出
#org.slf4j.simpleLogger.logFile=System.out

# 日期时间格式
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss

# 显示日志级别
org.slf4j.simpleLogger.showDateTime=true

# 显示线程名
org.slf4j.simpleLogger.showThreadName=false

# 显示日志名称
org.slf4j.simpleLogger.showLogName=true

# 显示短日志名称
org.slf4j.simpleLogger.showShortLogName=false

# 日志级别在输出中的字段宽度
org.slf4j.simpleLogger.levelInBrackets=true